src/main/java/com/igestao/model/Lancamento.java
package com.igestao.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.DecimalMin;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotEmpty;



@Entity
@Table(name = "lancamento")
public class Lancamento implements Serializable{

	
	private static final long serialVersionUID = 1L;
	
	private Long id;
	private Pessoa pessoa;
	private String descricao;
	private BigDecimal valor;
	private TipoLancamento tipo;
	private Date dataVencimento;
	private Date dataPagamento;
	
	@Id
	@GeneratedValue
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	
	@ManyToOne(optional = false)
	@JoinColumn(name = "pessoa_id")
	public Pessoa getPessoa() {
		return pessoa;
	}
	public void setPessoa(Pessoa pessoa) {
		this.pessoa = pessoa;
	}
	
	@NotEmpty
	@Size(max = 80)
	@Column(length = 80, nullable = false)
	public String getDescricao() {
		return descricao;
	}
	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}
	
	@NotNull
	@DecimalMin("0")
	@Column(precision = 10, scale = 2, nullable = false)
	public BigDecimal getValor() {
		return valor;
	}
	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}
	
	@NotNull
	@Enumerated(EnumType.STRING)
	@Column(nullable = false)
	public TipoLancamento getTipo() {
		return tipo;
	}
	public void setTipo(TipoLancamento tipo) {
		this.tipo = tipo;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "data_vencimento", nullable = false)
	public Date getDataVencimento() {
		return dataVencimento;
	}
	public void setDataVencimento(Date dataVencimento) {
		this.dataVencimento = dataVencimento;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "data_pagamento", nullable = true)
	public Date getDataPagamento() {
		return dataPagamento;
	}
	public void setDataPagamento(Date dataPagamento) {
		this.dataPagamento = dataPagamento;
	}
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((dataPagamento == null) ? 0 : dataPagamento.hashCode());
		result = prime * result
				+ ((dataVencimento == null) ? 0 : dataVencimento.hashCode());
		result = prime * result
				+ ((descricao == null) ? 0 : descricao.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((pessoa == null) ? 0 : pessoa.hashCode());
		result = prime * result + ((tipo == null) ? 0 : tipo.hashCode());
		result = prime * result + ((valor == null) ? 0 : valor.hashCode());
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Lancamento other = (Lancamento) obj;
		if (dataPagamento == null) {
			if (other.dataPagamento != null)
				return false;
		} else if (!dataPagamento.equals(other.dataPagamento))
			return false;
		if (dataVencimento == null) {
			if (other.dataVencimento != null)
				return false;
		} else if (!dataVencimento.equals(other.dataVencimento))
			return false;
		if (descricao == null) {
			if (other.descricao != null)
				return false;
		} else if (!descricao.equals(other.descricao))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (pessoa == null) {
			if (other.pessoa != null)
				return false;
		} else if (!pessoa.equals(other.pessoa))
			return false;
		if (tipo != other.tipo)
			return false;
		if (valor == null) {
			if (other.valor != null)
				return false;
		} else if (!valor.equals(other.valor))
			return false;
		return true;
	}
	
	

}

src/main/java/com/igestao/model/Pessoa.java
package com.igestao.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotEmpty;

@Entity
@Table(name = "pessoa")
public class Pessoa implements Serializable {

	
	private static final long serialVersionUID = 1L;
	
	private Long id;
	private String nome;
	
	@Id
	@GeneratedValue
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	@NotEmpty
	@Size(max = 60)
	@Column(length = 60, nullable = false)
	public String getNome() {
		return nome;
	}
	public void setNome(String nome) {
		this.nome = nome;
	}
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((nome == null) ? 0 : nome.hashCode());
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Pessoa other = (Pessoa) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (nome == null) {
			if (other.nome != null)
				return false;
		} else if (!nome.equals(other.nome))
			return false;
		return true;
	}
	
	

}

src/main/java/com/igestao/model/TipoLancamento.java
package com.igestao.model;

public enum TipoLancamento {
	
	RECEITA, DESPESA

}

src/main/java/com/igestao/controller/CadastroLancamentoBean.java
package com.igestao.controller;

import java.io.Serializable;
import java.util.List;


import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.event.ValueChangeEvent;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.EntityManager;


import com.igestao.model.Lancamento;
import com.igestao.model.Pessoa;
import com.igestao.model.TipoLancamento;
import com.igestao.repository.Pessoas;
import com.igestao.service.CadastroLancamentos;
import com.igestao.service.NegocioException;
import com.igestao.util.JpaUtil;

@Named
@javax.faces.view.ViewScoped
public class CadastroLancamentoBean implements Serializable {

	private static final long serialVersionUID = 1L;

	@Inject
	private CadastroLancamentos cadastro;
	@Inject
	private Pessoas pessoas;

	private Lancamento lancamento = new Lancamento();
	private List<Pessoa> todasPessoas;

	public void descricaoModificada(ValueChangeEvent event) {
		System.out.println("Valor antigo: " + event.getOldValue());
		System.out.println("Novo valor: " + event.getNewValue());
	}

	/*
	 * Carrega uma lista com todas as pessoas cadastradas. Usaremos essa lista
	 * para preencher o menu de pessoas na página.
	 */
	public void prepararCadastro() {
		EntityManager manager = JpaUtil.getEntityManager();
		try {
			Pessoas pessoas = new Pessoas(manager);
			this.todasPessoas = pessoas.todas();
		} finally {
			manager.close();
		}
	}

	public void salvar() {
		FacesContext context = FacesContext.getCurrentInstance();
		try {
			this.cadastro.salvar(this.lancamento);
			this.lancamento = new Lancamento();
			context.addMessage(null, new FacesMessage(
					"Lançamento salvo com sucesso!"));
		} catch (NegocioException e) {
			FacesMessage mensagem = new FacesMessage(e.getMessage());
			mensagem.setSeverity(FacesMessage.SEVERITY_ERROR);
			context.addMessage(null, mensagem);
		}
	}

	public List<Pessoa> getTodasPessoas() {
		return this.todasPessoas;
	}

	public TipoLancamento[] getTiposLancamentos() {
		return TipoLancamento.values();
	}

	public Lancamento getLancamento() {
		return lancamento;
	}

	public void setLancamento(Lancamento lancamento) {
		this.lancamento = lancamento;
	}

}

src/main/java/com/igestao/controller/ConsultaLancamentosBean.java
package com.igestao.controller;

import java.io.Serializable;
import java.util.List;

import javax.faces.bean.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;


import com.igestao.model.Lancamento;
import com.igestao.repository.Lancamentos;

@Named
@ViewScoped
public class ConsultaLancamentosBean implements Serializable{

	private static final long serialVersionUID = 1L;
	
	@Inject
	private Lancamentos lancamentosRepository;
	private List<Lancamento> lancamentos;
	
	public void consultar() {

		this.lancamentos = lancamentosRepository.todos();
		
	}
	public List<Lancamento> getLancamentos() {
		return lancamentos;
	}
	

}

src/main/webapp/CadastroLancamento.xhtml
<!DOCTYPE html>
<ui:composition template="/WEB-INF/template/Layout.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
	<f:metadata>
		<f:viewAction action="#{cadastroLancamentoBean.prepararCadastro}" />
	</f:metadata>

	<ui:define name="titulo">Cadastro de lançamento</ui:define>
	<ui:define name="corpo">
		<h1>Cadastro de lançamento</h1>
		<h:form id="frm">
			<h:messages showDetail="false" showSummary="true" />
			<h:panelGrid columns="2">
				<h:outputLabel value="Tipo" />
				<h:selectOneRadio value="#{cadastroLancamentoBean.lancamento.tipo}"
					label="Tipo do lançamento">
					<f:selectItems value="#{cadastroLancamentoBean.tiposLancamentos}"
						var="tipoLancamento" itemValue="#{tipoLancamento}" />
				</h:selectOneRadio>
				<h:outputLabel value="Pessoa" />
				<h:selectOneMenu value="#{cadastroLancamentoBean.lancamento.pessoa}"
					label="Pessoa">
					<f:selectItem itemLabel="Selecione" noSelectionOption="true" />
					<f:selectItems value="#{cadastroLancamentoBean.todasPessoas}"
						var="pessoa" itemValue="#{pessoa}" itemLabel="#{pessoa.nome}" />
				</h:selectOneMenu>
				<h:outputLabel value="Descrição" />

				<h:inputText size="60" label="Descrição"
					value="#{cadastroLancamentoBean.lancamento.descricao}"
					valueChangeListener="#{cadastroLancamentoBean.descricaoModificada}" 
					immediate="true" />
				<h:outputLabel value="Valor" />
				<h:inputText size="12"
					value="#{cadastroLancamentoBean.lancamento.valor}" label="Valor">
					<f:convertNumber locale="pt_BR" maxFractionDigits="2"
						minFractionDigits="2" />
				</h:inputText>
				<h:outputLabel value="Data de vencimento" />
				<h:inputText size="12"
					value="#{cadastroLancamentoBean.lancamento
.dataVencimento}"
					label="Data de vencimento">
					<f:convertDateTime pattern="dd/MM/yyyy"
						timeZone="America/Sao_Paulo" />
				</h:inputText>
				<h:outputLabel value="Data de pagamento" />
				<h:inputText size="12"
					value="#{cadastroLancamentoBean.lancamento
.dataPagamento}"
					label="Data de pagamento">
					<f:convertDateTime pattern="dd/MM/yyyy"
						timeZone="America/Sao_Paulo" />
				</h:inputText>
				<h:outputLabel />
				<h:commandButton value="Salvar"
					action="#{cadastroLancamentoBean.salvar}" />
			</h:panelGrid>
		</h:form>
	</ui:define>
</ui:composition>

src/main/webapp/ConsultaLancamentos.xhtml
<!DOCTYPE html>
<ui:composition template="/WEB-INF/template/Layout.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
	<f:metadata>
		<f:viewAction action="#{consultaLancamentosBean.consultar}" />
	</f:metadata>
	<ui:define name="titulo">Consulta de lançamentos</ui:define>
	<ui:define name="corpo">
		<h1>Consulta de lançamentos</h1>
		<h:form id="frm">
			<h:dataTable value="#{consultaLancamentosBean.lancamentos}"
				var="lancamento" border="1" cellspacing="0" cellpadding="2">
				<h:column>
					<f:facet name="header">
						<h:outputText value="Pessoa" />
					</f:facet>

					<h:outputText value="#{lancamento.pessoa.nome}" />
				</h:column>
				<h:column>
					<f:facet name="header">
						<h:outputText value="Descrição" />
					</f:facet>
					<h:outputText value="#{lancamento.descricao}" />
				</h:column>
				<h:column>
					<f:facet name="header">
						<h:outputText value="Tipo" />
					</f:facet>
					<h:outputText value="#{lancamento.tipo}" />
				</h:column>
				<h:column>
					<f:facet name="header">
						<h:outputText value="Valor" />
					</f:facet>
					<h:outputText value="#{lancamento.valor}" />
				</h:column>
				<h:column>
					<f:facet name="header">
						<h:outputText value="Data de vencimento" />
					</f:facet>
					<h:outputText value="#{lancamento.dataVencimento}" />
				</h:column>
				<h:column>
					<f:facet name="header">
						<h:outputText value="Data de pagamento" />
					</f:facet>
					<h:outputText value="#{lancamento.dataPagamento}" />
				</h:column>
			</h:dataTable>
		</h:form>
	</ui:define>
</ui:composition>

src/main/webapp/WEB-INF/template/Layout.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
<h:head>
	<title><ui:insert name="titulo">Sistema Financeiro</ui:insert>
	</title>
	<h:outputStylesheet library="css" name="estilo.css" />
</h:head>
<h:body>
	<header>

		<h:graphicImage library="images" name="logo.png" />
	</header>
	<div id="conteudo">
		<ui:insert name="corpo" />
	</div>
	<footer> Sistema Financeiro - AlgaWorks </footer>
</h:body>
</html>